apiVersion: v1
kind: Service
metadata:
  name: prometheus
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Adjust based on your cloud provider
spec:
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer  # This will allocate an external IP
