apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 2
  version: v2.22.1
  serviceAccountName: prometheus
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
      memory: 400Mi
  securityContext:
    fsGroup: 2000
    runAsUser: 1000
    runAsNonRoot: true
  serviceMonitorSelector: {}
  additionalScrapeConfigs:
    - job_name: 'node-exporter'
      static_configs:
        - targets:
            - 'node-exporter:9100'  # Adjust if necessary
  evaluationInterval: 30s
  image: quay.io/prometheus/prometheus:v2.22.1
  scrapeInterval: 30s
  portName: web
